/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ASUS
 */

public class Laboratorios extends javax.swing.JFrame  {

    /**
     * Creates new form reservas
     */
    public Laboratorios() {
    initComponents();
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReservas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnClean = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        cbxTipo = new javax.swing.JComboBox<String>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLabs = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbxBlock = new javax.swing.JComboBox<Modelos.Block>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReservas.setBackground(new java.awt.Color(43, 43, 43));
        panelReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Reborn", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aulas");
        panelReservas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, 78));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-sitio-fisei-2020.png"))); // NOI18N
        panelReservas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 490, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.3F);
        panelReservas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 161, 16, 385));

        btnClean.setBackground(new java.awt.Color(147, 10, 13));
        btnClean.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setText("Limpiar");
        btnClean.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 111, -1));

        btnEdit.setBackground(new java.awt.Color(43, 43, 43));
        btnEdit.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 111, -1));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo");
        panelReservas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        txtName.setBackground(new java.awt.Color(147, 10, 13));
        txtName.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        panelReservas.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 240, 220, 25));

        txtCode.setBackground(new java.awt.Color(147, 10, 13));
        txtCode.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtCode.setForeground(new java.awt.Color(255, 255, 255));
        txtCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        panelReservas.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 288, 220, 25));

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Codigo");
        panelReservas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 272, -1, -1));

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bloque");
        panelReservas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nombre:");
        panelReservas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 224, -1, -1));

        jLabel17.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Datos Aulas");
        panelReservas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 208, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(0.3F);
        panelReservas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 843, 16));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setAlignmentX(0.3F);
        panelReservas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 544, 843, 16));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setAlignmentX(0.3F);
        panelReservas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 20, 385));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setAlignmentX(0.3F);
        panelReservas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 16, 384));

        cbxTipo.setBackground(new java.awt.Color(147, 10, 13));
        cbxTipo.setFont(new java.awt.Font("Constantia", 0, 17)); // NOI18N
        cbxTipo.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Laboratorio", "Aula", "Aula especial" }));
        cbxTipo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cbxTipo.setPreferredSize(new java.awt.Dimension(72, 29));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        panelReservas.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 220, 25));

        btnSearch.setBackground(new java.awt.Color(147, 10, 13));
        btnSearch.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Buscar");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 111, -1));

        tbLabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbLabs);

        panelReservas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 560, 360));

        btnAdd.setBackground(new java.awt.Color(147, 10, 13));
        btnAdd.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Guardar");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 111, -1));

        btnDelete.setBackground(new java.awt.Color(43, 43, 43));
        btnDelete.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 111, -1));

        cbxBlock.setBackground(new java.awt.Color(147, 10, 13));
        cbxBlock.setFont(new java.awt.Font("Constantia", 0, 17)); // NOI18N
        cbxBlock.setForeground(new java.awt.Color(255, 255, 255));
        cbxBlock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cbxBlock.setPreferredSize(new java.awt.Dimension(72, 29));
        cbxBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBlockActionPerformed(evt);
            }
        });
        panelReservas.add(cbxBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 340, 220, 25));

        btnCancelar.setBackground(new java.awt.Color(43, 43, 43));
        btnCancelar.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Regresar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 111, -1));

        getContentPane().add(panelReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 928, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void cbxBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBlockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnClean;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnSearch;
    public javax.swing.JComboBox<Modelos.Block> cbxBlock;
    public javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel panelReservas;
    public javax.swing.JTable tbLabs;
    public javax.swing.JTextField txtCode;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
