/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ASUS
 */


public class Reservas extends javax.swing.JFrame  {

    /**
     * Creates new form reservas
     */
    public Reservas() {
    initComponents();
    this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReservas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        btReservas = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtHoraFin = new javax.swing.JTextField();
        txtHoraInicio = new javax.swing.JTextField();
        txtCedulaResponsable = new javax.swing.JTextField();
        txtFechaReserva = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        cbTipo_Reserva = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        txtMateria = new javax.swing.JTextField();
        cbCarreras = new javax.swing.JComboBox<>();
        cbCargo = new javax.swing.JComboBox<>();
        txtApellidoResponsable = new javax.swing.JTextField();
        txtNombreRespon = new javax.swing.JTextField();
        txtEdificio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jlMensaje = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReservas.setBackground(new java.awt.Color(212, 215, 224));
        panelReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reservas");
        panelReservas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 78));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Edifici0:");
        panelReservas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 224, 64, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora inicio:");
        panelReservas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 416, -1, -1));

        bnRegresar.setBackground(new java.awt.Color(212, 215, 224));
        bnRegresar.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        bnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        bnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar-icon.png"))); // NOI18N
        bnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        bnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRegresarActionPerformed(evt);
            }
        });
        panelReservas.add(bnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 112, 32, 32));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora fin:");
        panelReservas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 464, -1, -1));

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha de reserva:");
        panelReservas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 368, -1, -1));

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripción");
        panelReservas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-sitio-fisei-2020.png"))); // NOI18N
        panelReservas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(0.3F);
        panelReservas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 161, 16, 385));

        jScrollPane2.setBackground(new java.awt.Color(43, 43, 43));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setForeground(new java.awt.Color(43, 43, 43));

        textDescripcion.setBackground(new java.awt.Color(237, 233, 233));
        textDescripcion.setColumns(20);
        textDescripcion.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        textDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        textDescripcion.setLineWrap(true);
        textDescripcion.setRows(5);
        textDescripcion.setToolTipText("");
        textDescripcion.setWrapStyleWord(true);
        textDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        textDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        textDescripcion.setDisabledTextColor(new java.awt.Color(147, 10, 13));
        textDescripcion.setPreferredSize(new java.awt.Dimension(302, 117));
        jScrollPane2.setViewportView(textDescripcion);

        panelReservas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 336, 240, 96));

        btReservas.setBackground(new java.awt.Color(147, 10, 13));
        btReservas.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btReservas.setForeground(new java.awt.Color(255, 255, 255));
        btReservas.setText("Reservar");
        btReservas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 480, 111, -1));

        btCancelar.setBackground(new java.awt.Color(43, 43, 43));
        btCancelar.setFont(new java.awt.Font("Constantia", 1, 15)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Limpiar");
        btCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        panelReservas.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 480, 111, -1));

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Usuario:");
        panelReservas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 128, -1, -1));

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Laboratorio:");
        panelReservas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 272, 112, -1));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipo:");
        panelReservas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 224, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(212, 215, 224));
        txtUsuario.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setText("JUAN");
        txtUsuario.setBorder(null);
        txtUsuario.setCaretColor(new java.awt.Color(43, 43, 43));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelReservas.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 128, -1, -1));

        txtHoraFin.setBackground(new java.awt.Color(237, 233, 233));
        txtHoraFin.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtHoraFin.setForeground(new java.awt.Color(0, 0, 0));
        txtHoraFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHoraFin.setBorder(null);
        txtHoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraFinActionPerformed(evt);
            }
        });
        panelReservas.add(txtHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 480, 192, 25));

        txtHoraInicio.setBackground(new java.awt.Color(237, 233, 233));
        txtHoraInicio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtHoraInicio.setForeground(new java.awt.Color(0, 0, 0));
        txtHoraInicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHoraInicio.setBorder(null);
        txtHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicioActionPerformed(evt);
            }
        });
        panelReservas.add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 432, 192, 25));

        txtCedulaResponsable.setBackground(new java.awt.Color(237, 233, 233));
        txtCedulaResponsable.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtCedulaResponsable.setForeground(new java.awt.Color(0, 0, 0));
        txtCedulaResponsable.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedulaResponsable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelReservas.add(txtCedulaResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 240, 192, 25));

        txtFechaReserva.setBackground(new java.awt.Color(237, 233, 233));
        txtFechaReserva.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtFechaReserva.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaReserva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFechaReserva.setBorder(null);
        txtFechaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaReservaActionPerformed(evt);
            }
        });
        panelReservas.add(txtFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 384, 192, 25));

        txtLaboratorio.setBackground(new java.awt.Color(237, 233, 233));
        txtLaboratorio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtLaboratorio.setForeground(new java.awt.Color(0, 0, 0));
        txtLaboratorio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLaboratorio.setBorder(null);
        txtLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaboratorioActionPerformed(evt);
            }
        });
        panelReservas.add(txtLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 288, 192, 25));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LUGAR");
        panelReservas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 176, 192, -1));

        jLabel13.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Apellido");
        panelReservas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cédula:");
        panelReservas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 224, -1, -1));

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Carrera:");
        panelReservas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 368, -1, -1));

        jLabel16.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Materia:");
        panelReservas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 272, -1, -1));

        jLabel17.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("RAZON");
        panelReservas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 176, 208, -1));

        jLabel18.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("HORARIO");
        panelReservas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 336, 128, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(0.3F);
        panelReservas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 843, 16));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setAlignmentX(0.3F);
        panelReservas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 544, 843, 16));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setAlignmentX(0.3F);
        panelReservas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 16, 385));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setAlignmentX(0.3F);
        panelReservas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 16, 384));

        cbTipo_Reserva.setBackground(new java.awt.Color(237, 233, 233));
        cbTipo_Reserva.setFont(new java.awt.Font("Constantia", 0, 17)); // NOI18N
        cbTipo_Reserva.setForeground(new java.awt.Color(0, 0, 0));
        cbTipo_Reserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reserva", "Horario" }));
        cbTipo_Reserva.setSelectedIndex(-1);
        cbTipo_Reserva.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cbTipo_Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipo_ReservaActionPerformed(evt);
            }
        });
        panelReservas.add(cbTipo_Reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 240, 192, 25));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setAlignmentX(0.3F);
        panelReservas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 160, 16, 385));

        txtMateria.setBackground(new java.awt.Color(237, 233, 233));
        txtMateria.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtMateria.setForeground(new java.awt.Color(0, 0, 0));
        txtMateria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });
        panelReservas.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 288, 192, 25));

        cbCarreras.setBackground(new java.awt.Color(237, 233, 233));
        cbCarreras.setFont(new java.awt.Font("Constantia", 0, 17)); // NOI18N
        cbCarreras.setForeground(new java.awt.Color(0, 0, 0));
        cbCarreras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cbCarreras.setPreferredSize(new java.awt.Dimension(72, 29));
        panelReservas.add(cbCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 384, 192, 25));

        cbCargo.setBackground(new java.awt.Color(237, 233, 233));
        cbCargo.setFont(new java.awt.Font("Constantia", 0, 17)); // NOI18N
        cbCargo.setForeground(new java.awt.Color(0, 0, 0));
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docente", "Estudiante", "Otros" }));
        cbCargo.setSelectedIndex(-1);
        cbCargo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoActionPerformed(evt);
            }
        });
        panelReservas.add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 432, 192, 25));

        txtApellidoResponsable.setBackground(new java.awt.Color(237, 233, 233));
        txtApellidoResponsable.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtApellidoResponsable.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoResponsable.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoResponsable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtApellidoResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoResponsableActionPerformed(evt);
            }
        });
        panelReservas.add(txtApellidoResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 336, 192, 25));

        txtNombreRespon.setBackground(new java.awt.Color(237, 233, 233));
        txtNombreRespon.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtNombreRespon.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreRespon.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreRespon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNombreRespon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreResponActionPerformed(evt);
            }
        });
        panelReservas.add(txtNombreRespon, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 288, 192, 25));

        txtEdificio.setBackground(new java.awt.Color(237, 233, 233));
        txtEdificio.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        txtEdificio.setForeground(new java.awt.Color(0, 0, 0));
        txtEdificio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEdificio.setBorder(null);
        txtEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdificioActionPerformed(evt);
            }
        });
        panelReservas.add(txtEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 240, 192, 25));

        jLabel19.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("RESPONSABLE");
        panelReservas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 176, 208, -1));

        jlMensaje.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jlMensaje.setForeground(new java.awt.Color(0, 0, 0));
        jlMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelReservas.add(jlMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 416, 16));

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Cargo:");
        panelReservas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 416, -1, -1));

        jLabel21.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombre:");
        panelReservas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 272, -1, -1));

        getContentPane().add(panelReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 928, 576));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaboratorioActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void cbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargoActionPerformed

    private void txtEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdificioActionPerformed

    private void txtNombreResponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreResponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreResponActionPerformed

    private void txtApellidoResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoResponsableActionPerformed

    private void txtFechaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaReservaActionPerformed

    private void txtHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioActionPerformed

    private void txtHoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraFinActionPerformed

    private void cbTipo_ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipo_ReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipo_ReservaActionPerformed

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void bnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bnRegresar;
    public javax.swing.JButton btCancelar;
    public javax.swing.JButton btReservas;
    public javax.swing.JComboBox<String> cbCargo;
    public javax.swing.JComboBox<Modelos.Carrera> cbCarreras;
    public javax.swing.JComboBox<String> cbTipo_Reserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel jlMensaje;
    private javax.swing.JPanel panelReservas;
    public javax.swing.JTextArea textDescripcion;
    public javax.swing.JTextField txtApellidoResponsable;
    public javax.swing.JTextField txtCedulaResponsable;
    public javax.swing.JTextField txtEdificio;
    public javax.swing.JTextField txtFechaReserva;
    public javax.swing.JTextField txtHoraFin;
    public javax.swing.JTextField txtHoraInicio;
    public javax.swing.JTextField txtLaboratorio;
    public javax.swing.JTextField txtMateria;
    public javax.swing.JTextField txtNombreRespon;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
